spring.profiles.active: security-auth-google,security-auth-github,security-jwt

server.servlet.context-path: /api

security.paths.logout: "/auth/logout"
security.paths.auth.to.skip: "/auth,/github-auth/**,/google-auth/**,/auth/csrf,/swagger-ui/**,/v2/api-docs,/swagger-resources,/swagger-resources/configuration/ui,/swagger-resources/configuration/security,/h2-console/**"
security.paths.csrf.to.skip: "/h2-console/**,/swagger-ui/**,/google-auth/consent/callback,/github-auth/consent/callback"

spring.datasource.driverClassName: org.h2.Driver
spring.datasource.password: password
spring.datasource.url: "jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;"
spring.datasource.username: sa
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto: create-drop
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

